### ISSUE TITLE
Want to Open the Config /zl

### ISSUE THREAD

**Issue by TaZzDE** [Chris221/ZeldaLoot-BCC#1]
1x ZeldaLoot_BCC\ConfigPanel_scripts.lua:5: attempt to index field 'sounds' (a nil value)
[string "@ZeldaLoot_BCC\ConfigPanel_scripts.lua"]:5: in function `update_config'
[string "@ZeldaLoot_BCC\ConfigPanel_scripts.lua"]:63: in function `show_zl_frame'
[string "@ZeldaLoot_BCC\SlashCommands.lua"]:12: in function `?'
[string "@FrameXML\ChatFrame.lua"]:4825: in function <FrameXML\ChatFrame.lua:4771>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4488: in function <FrameXML\ChatFrame.lua:4487>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4524: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
set = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'sounds' (a nil value)"

**Comment by Chris221** [comment]
I have fixed the bug in v1.1.1

**Comment by TaZzDE** [comment]
Thx works fine :-)
